// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function isDiv(x, y) {
  return Caml_int32.mod_(x, y) === 0;
}

function isLeapYear(year) {
  if (isDiv(year, 4) && !isDiv(year, 100)) {
    return true;
  } else if (isDiv(year, 100)) {
    return isDiv(year, 400);
  } else {
    return false;
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
