// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function period(planet) {
  switch (planet) {
    case 0 : 
        return 0.2408467;
    case 1 : 
        return 0.61519726;
    case 2 : 
        return 1.0;
    case 3 : 
        return 1.8808158;
    case 4 : 
        return 11.862615;
    case 5 : 
        return 29.447498;
    case 6 : 
        return 164.79132;
    case 7 : 
        return 84.016846;
    
  }
}

function ageOn(planet, sec) {
  return sec / 31557600.0 / period(planet);
}

exports.ageOn = ageOn;
/* No side effect */
