// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var HelloWorld$HelloWorld = require("../src/HelloWorld.bs.js");

describe("Hello World", (function () {
        return Jest.test("says hello", (function () {
                      return Jest.Expect[/* toBe */2]("Hello, World!", Jest.Expect[/* expect */0](HelloWorld$HelloWorld.hello(/* () */0)));
                    }));
      }));

/*  Not a pure module */
