// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Leap$Leap = require("../src/Leap.bs.js");

describe("Leap", (function () {
        Jest.test("year not divisible by 4: common year", (function () {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Leap$Leap.isLeapYear(2015)));
              }));
        Jest.test("year divisible by 4, not divisible by 100: leap year", (function () {
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Leap$Leap.isLeapYear(1996)));
              }));
        Jest.test("year divisible by 100, not divisible by 400: common year", (function () {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Leap$Leap.isLeapYear(2100)));
              }));
        return Jest.test("year divisible by 400: leap year", (function () {
                      return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Leap$Leap.isLeapYear(2000)));
                    }));
      }));

/*  Not a pure module */
